package com.dkostin.avro_viewer.app.util.schema;

import com.dkostin.avro_viewer.app.config.FilterPathValidator;
import com.dkostin.avro_viewer.app.config.FilterPredicateFactory;
import com.dkostin.avro_viewer.app.domain.model.fileinfo.SchemaNode;
import com.dkostin.avro_viewer.app.domain.model.filter.*;
import org.apache.avro.Schema;
import org.apache.avro.SchemaBuilder;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.GenericRecord;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;
import java.util.function.Predicate;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertFalse;

class SchemaCatalogContractTest {

    @Test
    void testAllCatalogPathsPassValidationAndPredicateCompilation() {
        Schema addressSchema = SchemaBuilder.record("Address").fields()
                .requiredString("city")
                .optionalString("zip")
                .endRecord();

        Schema itemSchema = SchemaBuilder.record("Item").fields()
                .requiredString("sku")
                .requiredDouble("price")
                .endRecord();

        Schema rootSchema = SchemaBuilder.record("Customer").fields()
                .requiredString("name")
                .name("address").type(addressSchema).noDefault()
                .name("items").type().array().items(itemSchema).noDefault()
                .name("tags").type().map().values().stringType().noDefault()
                .endRecord();

        // Sample record
        GenericRecord address = new GenericData.Record(addressSchema);
        address.put("city", "Kyiv");
        address.put("zip", "01001");

        GenericRecord item1 = new GenericData.Record(itemSchema);
        item1.put("sku", "SKU-1");
        item1.put("price", 99.9);

        GenericRecord customer = new GenericData.Record(rootSchema);
        customer.put("name", "Denis");
        customer.put("address", address);
        customer.put("items", List.of(item1));
        customer.put("tags", Map.of("env", "prod"));

        List<SchemaNode> nodes = SchemaCatalog.paths(rootSchema);
        assertFalse(nodes.isEmpty());

        FilterPredicateFactory predicateFactory = new FilterPredicateFactory();

        for (SchemaNode node : nodes) {
            String path = node.path();

            // 1. Must pass FilterPathValidator
            List<FilterGroup> group = List.of(new FilterGroup(List.of(
                    new FilterCriterion(FilterOption.ofField(path), MatchOperation.CONTAINS, "test")
            )));
            assertDoesNotThrow(() -> FilterPathValidator.validate(rootSchema, group),
                    "Path generated by SchemaCatalog failed FilterPathValidator: " + path);

            // 2. Must compile and evaluate cleanly on record without throwing
            Predicate<GenericRecord> predicate = predicateFactory.compile(group);
            assertDoesNotThrow(() -> predicate.test(customer),
                    "Predicate failed to evaluate on record for path: " + path);
        }
    }
}
